name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Dineshk125
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Push generated snake files to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: snake-graphs
          path: dist
